GUISwitch($frmAttackConfig)
; Line above required

; Name your strategy
$StratComboText = "Standard farming strategies"
; List the number of tabs you are using
$StratTabs = "4"

; Format necessary for plugins:
; $StratComboText = $StratComboText & "|Plugin name"
; $StratTabs = $StratTabs & "|" & "# of tabs"

$pageSearch = GUICtrlCreateTabItem("Search Settings")
$DeadConditions = GUICtrlCreateGroup("Dead Base Conditions", 18, 65, 397, 135)
$chkDeadActivate = GUICtrlCreateCheckbox("Activate", 30, 85, 90, 17)
$lblDeadConditions = GUICtrlCreateLabel("Search for full collectors bases and ALL selected conditions", 120, 85, 380, 20)
$chkDeadGE = GUICtrlCreateCheckbox("Min Resources:", 30, 108, 100, 17)
$lblDeadMinGold = GUICtrlCreateLabel("Gold: ", 140, 110, 28, 17)
$txtDeadMinGold = GUICtrlCreateInput("50000", 170, 105, 50, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetLimit(-1, 6)
$cmbDead = GUICtrlCreateCombo("", 240, 105, 45, 21, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "And|Or", "And")
$lblDeadMinElixir = GUICtrlCreateLabel("Elixir: ", 300, 110, 28, 17)
$txtDeadMinElixir = GUICtrlCreateInput("50000", 330, 105, 50, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetLimit(-1, 6)
$chkDeadMeetDE = GUICtrlCreateCheckbox("Min Dark Elixir:", 30, 138, 95, 17)
$txtDeadMinDarkElixir = GUICtrlCreateInput("0", 130, 135, 60, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetLimit(-1, 6)
$chkDeadMeetTrophy = GUICtrlCreateCheckbox("Min Trophies:", 225, 138, 95, 17)
$txtDeadMinTrophy = GUICtrlCreateInput("0", 325, 135, 60, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$chkDeadMeetTH = GUICtrlCreateCheckbox("Max TH Level:", 30, 168, 95, 17)
$cmbDeadTH = GUICtrlCreateCombo("", 130, 165, 60, 21, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "4-6|7|8|9|10", "4-6")
$chkDeadMeetTHO = GUICtrlCreateCheckbox("TH Outside", 225, 168, 70, 17)
GUICtrlSetTip(-1, "Townhall must be on outer edges of base")
$chkDeadSnipe = GUICtrlCreateCheckbox("Snipe", 315, 168, 50, 17)
GUICtrlSetTip(-1, "If checked, will attack exterior townhall of dead base regardless of other settings")
GUICtrlSetState($chkDeadGE, $GUI_DISABLE)
GUICtrlSetState($txtDeadMinGold, $GUI_DISABLE)
GUICtrlSetState($cmbDead, $GUI_DISABLE)
GUICtrlSetState($txtDeadMinElixir, $GUI_DISABLE)
GUICtrlSetState($chkDeadMeetDE, $GUI_DISABLE)
GUICtrlSetState($txtDeadMinDarkElixir, $GUI_DISABLE)
GUICtrlSetState($chkDeadMeetTrophy, $GUI_DISABLE)
GUICtrlSetState($txtDeadMinTrophy, $GUI_DISABLE)
GUICtrlSetState($chkDeadMeetTH, $GUI_DISABLE)
GUICtrlSetState($cmbDeadTH, $GUI_DISABLE)
GUICtrlSetState($chkDeadMeetTHO, $GUI_DISABLE)
$AnyConditions = GUICtrlCreateGroup("Live Base Conditions", 18, 205, 397, 130)
$chkAnyActivate = GUICtrlCreateCheckbox("Activate", 30, 225, 90, 17)
$lblAnyConditions = GUICtrlCreateLabel("Search for any bases and ALL selected conditions", 120, 225, 380, 20)
$chkMeetGE = GUICtrlCreateCheckbox("Min Resources: ", 30, 248, 100, 17)
GUICtrlSetState(-1, $GUI_CHECKED)
$lblMinGold = GUICtrlCreateLabel("Gold:", 140, 250, 28, 17)
$txtMinGold = GUICtrlCreateInput("80000", 170, 245, 50, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetLimit(-1, 6)
$cmbAny = GUICtrlCreateCombo("", 240, 245, 45, 21, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "And|Or", "And")
$lblMinElixir = GUICtrlCreateLabel("Elixir:", 300, 250, 28, 17)
$txtMinElixir = GUICtrlCreateInput("80000", 330, 245, 50, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetLimit(-1, 6)
$chkMeetDE = GUICtrlCreateCheckbox("Min Dark Elixir:", 30, 278, 95, 17)
$txtMinDarkElixir = GUICtrlCreateInput("0", 130, 275, 60, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetLimit(-1, 6)
$chkMeetTrophy = GUICtrlCreateCheckbox("Min Trophies:", 225, 278, 95, 17)
$txtMinTrophy = GUICtrlCreateInput("0", 325, 275, 60, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetLimit(-1, 2)
$chkMeetTH = GUICtrlCreateCheckbox("Max TH Level:", 30, 308, 95, 17)
$cmbTH = GUICtrlCreateCombo("", 130, 305, 60, 21, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "4-6|7|8|9|10", "4-6")
$chkMeetTHO = GUICtrlCreateCheckbox("TH Outside", 225, 308, 70, 17)
GUICtrlSetTip(-1, "Townhall must be on outer edges of base")
$chkSnipe = GUICtrlCreateCheckbox("Snipe", 315, 308, 50, 17)
GUICtrlSetTip(-1, "If checked, will attack exterior townhall of live base regardless of other settings")
GUICtrlSetState($chkMeetGE, $GUI_DISABLE)
GUICtrlSetState($txtMinGold, $GUI_DISABLE)
GUICtrlSetState($cmbAny, $GUI_DISABLE)
GUICtrlSetState($txtMinElixir, $GUI_DISABLE)
GUICtrlSetState($chkMeetDE, $GUI_DISABLE)
GUICtrlSetState($txtMinDarkElixir, $GUI_DISABLE)
GUICtrlSetState($chkMeetTrophy, $GUI_DISABLE)
GUICtrlSetState($txtMinTrophy, $GUI_DISABLE)
GUICtrlSetState($chkMeetTH, $GUI_DISABLE)
GUICtrlSetState($cmbTH, $GUI_DISABLE)
GUICtrlSetState($chkMeetTHO, $GUI_DISABLE)
GUICtrlCreateGroup("", -99, -99, 1, 1)

;Attack Tab
$pageAttack = GUICtrlCreateTabItem("Attack Method")
$DeadDeploySettings = GUICtrlCreateGroup("Dead Base Deploy Settings", 15, 65, 390, 123)
$cmbDeadDeploy = GUICtrlCreateCombo("", 30, 80, 360, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Attack on a single side, penetrates through base|Attack on two sides, penetrates through base|Attack on three sides, gets outer and some inside of base|Attack on all sides equally, gets most of outer base|Mixed mode: limited on 4 sides then focus on 1 side", "Attack on all sides equally, gets most of outer base")
$cmbDeadAlgorithm = GUICtrlCreateCombo("", 30, 110, 360, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Archers|Barbarians|Goblins|Barbarians + Archers|Barb + Arch + Goblin + Giant|Barb + Arch + Giant|Barb + Arch + Goblin|Barb + Arch + Goblin + Giant + Wallbreakers|Use Barracks|Use All Troops", "Use All Troops") ;"Archers|Barbarians|Goblins|Barbarians + Archers|Barb + Arch + Goblin + Giant|Barb + Arch + Giant|Barb + Arch + Goblin|Barb + Arch + Goblin + Giant + Wallbreakers|Use Barracks"
$chkDeadUseKing = GUICtrlCreateCheckbox("Attack with King", 30, 140, 150, 17)
$chkDeadUseQueen = GUICtrlCreateCheckbox("Attack with Queen", 200, 140, 105, 17)
$chkDeadUseClanCastle = GUICtrlCreateCheckbox("Attack with Clan Castle troops", 30, 160, 160, 17)
$cmbDeadAttackTH = GUICtrlCreateCombo("", 200, 160, 190, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Don't attack TH|Limited TH attack|Full TH attack")
GUICtrlCreateGroup("", -99, -99, 1, 1)

$AnyDeploySettings = GUICtrlCreateGroup("Other Base Deploy Settings", 15, 188, 390, 123)
$cmbDeploy = GUICtrlCreateCombo("", 30, 207, 360, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Attack on a single side, penetrates through base|Attack on two sides, penetrates through base|Attack on three sides, gets outer and some inside of base|Attack on all sides equally, gets most of outer base|Mixed mode: limited on 4 sides then focus on 1 side", "Attack on all sides equally, gets most of outer base")
$cmbAlgorithm = GUICtrlCreateCombo("", 30, 237, 360, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Archers|Barbarians|Goblins|Barbarians + Archers|Barb + Arch + Goblin + Giant|Barb + Arch + Giant|Barb + Arch + Goblin|Barb + Arch + Goblin + Giant + Wallbreakers|Use Barracks|Use All Troops", "Use All Troops") ;"Archers|Barbarians|Goblins|Barbarians + Archers|Barb + Arch + Goblin + Giant|Barb + Arch + Giant|Barb + Arch + Goblin|Barb + Arch + Goblin + Giant + Wallbreakers|Use Barracks"
$chkUseKing = GUICtrlCreateCheckbox("Attack with King", 30, 265, 97, 17)
$chkUseQueen = GUICtrlCreateCheckbox("Attack with Queen", 200, 265, 105, 17)
$chkUseClanCastle = GUICtrlCreateCheckbox("Attack with Clan Castle troops", 30, 285, 160, 17)
$cmbAttackTH = GUICtrlCreateCombo("", 200, 285, 190, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Don't attack TH|Limited TH attack|Full TH attack")
GUICtrlCreateGroup("", -99, -99, 1, 1)

;Troops Tab
$pageTraining = GUICtrlCreateTabItem("Troop Training")
$Barracks = GUICtrlCreateGroup("Troops", 20, 65, 185, 194)
$lblBarbarians = GUICtrlCreateLabel("Barbarians :", 30, 93, 60, 17)
$lblArchers = GUICtrlCreateLabel("Archers :", 30, 118, 46, 17)
$lblGoblins = GUICtrlCreateLabel("Goblins :", 30, 143, 45, 17)
$lblCapacity = GUICtrlCreateLabel("Camp Capacity :", 30, 168, 95, 17)
$lblRaidcap = GUICtrlCreateLabel("Raid Capacity :", 30, 193, 95, 17)
$cmbRaidcap = GUICtrlCreateCombo("", 120, 190, 56, 21, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "10|20|30|40|50|60|70|80|90|100", "100")
$lblPercentCapacity = GUICtrlCreateLabel("%", 180, 193, 12, 17)
$txtBarbarians = GUICtrlCreateInput("30", 120, 90, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1, $GUI_DISABLE)
$txtArchers = GUICtrlCreateInput("60", 120, 115, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1, $GUI_DISABLE)
$txtGoblins = GUICtrlCreateInput("10", 120, 140, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState(-1, $GUI_DISABLE)
$txtCapacity = GUICtrlCreateInput("0", 120, 165, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
$lblPercentBarbarians = GUICtrlCreateLabel("%", 180, 93, 12, 17)
$lblPercentArchers = GUICtrlCreateLabel("%", 180, 118, 12, 17)
$lblPercentGoblins = GUICtrlCreateLabel("%", 180, 133, 12, 17)
$cmbTroopComp = GUICtrlCreateCombo("", 40, 225, 156, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUISetOnEvent(-1, "cmbTroopComp")
GUICtrlSetData(-1, "Archers|Barbarians|Goblins|B.Arch|B.A.G.G.|B.A.Giant|B.A.Goblin|B.A.G.G.Wall|Use Barracks|Custom Troops", "Use Barracks") ;"Archers|Barbarians|Goblins|B.Arch|B.A.G.G.|B.A.Giant|B.A.Goblin|B.A.G.G.Wall|Use Barracks|Custom Troops"
GUICtrlCreateGroup("", -99, -99, 1, 1)

$OtherTroops = GUICtrlCreateGroup("Other Troops", 210, 65, 185, 70)
$lblGiants = GUICtrlCreateLabel("Number of Giants:", 215, 84, 89, 17)
$lblWallBreakers = GUICtrlCreateLabel("Number of Wall Breakers:", 215, 109, 125, 17)
$txtNumGiants = GUICtrlCreateInput("4", 340, 81, 46, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER))
GUICtrlSetState(-1, $GUI_DISABLE)
$txtNumWallbreakers = GUICtrlCreateInput("4", 340, 106, 46, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER))
GUICtrlSetState(-1, $GUI_DISABLE)

GUICtrlCreateGroup("", -99, -99, 1, 1)

$BarrackGroup = GUICtrlCreateGroup("Barracks", 210, 137, 185, 122)
$lblBarrack1 = GUICtrlCreateLabel("Barrack 1:", 220, 158, 53, 17)
$lblBarrack2 = GUICtrlCreateLabel("Barrack 2:", 220, 183, 53, 17)
$lblBarrack3 = GUICtrlCreateLabel("Barrack 3:", 220, 208, 53, 17)
$lblBarrack4 = GUICtrlCreateLabel("Barrack 4:", 220, 233, 53, 17)
$cmbBarrack1 = GUICtrlCreateCombo("", 275, 155, 110, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breaker|Balloon(Training Only)|Wizard(Training Only)|Healer(Training Only)|Dragon(Training Only)|Pekka(Training Only)|Nothing", "Barbarians")
$cmbBarrack2 = GUICtrlCreateCombo("", 275, 180, 110, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breaker|Balloon(Training Only)|Wizard(Training Only)|Healer(Training Only)|Dragon(Training Only)|Pekka(Training Only)|Nothing", "Archers")
$cmbBarrack3 = GUICtrlCreateCombo("", 275, 205, 110, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breaker|Balloon(Training Only)|Wizard(Training Only)|Healer(Training Only)|Dragon(Training Only)|Pekka(Training Only)|Nothing", "Archers")
$cmbBarrack4 = GUICtrlCreateCombo("", 275, 230, 110, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breaker|Balloon(Training Only)|Wizard(Training Only)|Healer(Training Only)|Dragon(Training Only)|Pekka(Training Only)|Nothing", "Goblins")
GUICtrlCreateGroup("", -99, -99, 1, 1)

$BarrackCTGroup = GUICtrlCreateGroup("Custom Troop 2 / Not Available", 20, 259, 375, 121)
$lblBarrackJOE1 = GUICtrlCreateLabel("Barrack 1 :", 30, 278, 53, 17)
$lblBarrackJOE2 = GUICtrlCreateLabel("Barrack 2 :", 30, 303, 53, 17)
$lblBarrackJOE3 = GUICtrlCreateLabel("Barrack 3 :", 30, 328, 53, 17)
$lblBarrackJOE4 = GUICtrlCreateLabel("Barrack 4 :", 30, 353, 53, 17)
$lblBarrackBK1 = GUICtrlCreateLabel("the rest", 237, 278, 35, 17)
$lblBarrackBK2 = GUICtrlCreateLabel("the rest", 237, 303, 35, 17)
$lblBarrackBK3 = GUICtrlCreateLabel("the rest", 237, 328, 35, 17)
$lblBarrackBK4 = GUICtrlCreateLabel("the rest", 237, 353, 35, 17)

$txtBarrackJOE1 = GUICtrlCreateInput("2", 90, 275, 31, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetLimit(-1, 2)
GUICtrlSetState(-1, $GUI_DISABLE)
$txtBarrackJOE2 = GUICtrlCreateInput("2", 90, 300, 31, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetLimit(-1, 2)
GUICtrlSetState(-1, $GUI_DISABLE)
$txtBarrackJOE3 = GUICtrlCreateInput("2", 90, 325, 31, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetLimit(-1, 2)
GUICtrlSetState(-1, $GUI_DISABLE)
$txtBarrackJOE4 = GUICtrlCreateInput("2", 90, 350, 31, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetLimit(-1, 2)
GUICtrlSetState(-1, $GUI_DISABLE)

$cmbBarrackFT1 = GUICtrlCreateCombo("", 130, 275, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breaker|Nothing", "Giants")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbBarrackFT2 = GUICtrlCreateCombo("", 130, 300, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breaker|Nothing", "W.Breaker")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbBarrackFT3 = GUICtrlCreateCombo("", 130, 325, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breaker|Nothing", "Giants")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbBarrackFT4 = GUICtrlCreateCombo("", 130, 350, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breaker|Nothing", "W.Breaker")
GUICtrlSetState(-1, $GUI_DISABLE)

$cmbBarrackBK1 = GUICtrlCreateCombo("", 285, 275, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breaker|Nothing", "Barbarians")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbBarrackBK2 = GUICtrlCreateCombo("", 285, 300, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breaker|Nothing", "Archers")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbBarrackBK3 = GUICtrlCreateCombo("", 285, 325, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breaker|Nothing", "Barbarians")
GUICtrlSetState(-1, $GUI_DISABLE)
$cmbBarrackBK4 = GUICtrlCreateCombo("", 285, 350, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarians|Archers|Giants|Goblins|W.Breaker|Nothing", "Archers")
GUICtrlSetState(-1, $GUI_DISABLE)
GUICtrlCreateGroup("", -99, -99, 1, 1)

;Spells Tab
$pageStatsSetting = GUICtrlCreateTabItem("Spells")
$lblDEAccuracy = GUICtrlCreateGroup("Spell Factory", 20, 65, 375, 74)
$chkMakeSpells = GUICtrlCreateCheckbox("Make spells", 30, 85, 97, 17)
GUICtrlSetState(-1, $GUI_UNCHECKED)
$lblSpellCreate = GUICtrlCreateLabel("Spell to keep full:", 30, 112, 90, 17)
GUICtrlSetTip(-1, "Set to the spell you want made")
$cmbSpellCreate = GUICtrlCreateCombo("", 125, 108, 85, 21, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Lightning|Healing|Rage|Jump|Freeze", "Lightning")
$lblSpellCap = GUICtrlCreateLabel("Spell factory capacity:", 217, 87, 120, 17)
$txtSpellCap = GUICtrlCreateInput("3", 335, 85, 50, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))

$lblDEZap = GUICtrlCreateGroup("DE zapping", 20, 149, 375, 154)
$lblDENukeLimit = GUICtrlCreateLabel("Zap with spell if DE greater than:", 30, 169, 170, 17)
$txtDENukeLimit = GUICtrlCreateInput("2000", 197, 169, 51, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
$chkNukeOnly = GUICtrlCreateCheckbox("Allow zap only behavior", 30, 209, 180, 17)
$chkNukeOnlyWithFullArmy = GUICtrlCreateCheckbox("Only search base for zapping with full army", 30, 229, 250, 17)
GUICtrlSetState(-1, $GUI_UNCHECKED)
GUICtrlSetTip(-1, "If spell factory is full, will search for a camp to hit and run the DE storage")
$chkNukeAttacking = GUICtrlCreateCheckbox("Zap DE if already attacking", 30, 256, 180, 17)
GUICtrlSetState(-1, $GUI_UNCHECKED)
GUICtrlSetTip(-1, "Will zap DE storage during attack if you have more than number of spells below")
$lblSpellNumber = GUICtrlCreateLabel("Number of spells needed:", 30, 279, 170, 17)
$txtSpellNumber = GUICtrlCreateInput("3", 200, 275, 51, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))

$lblDEAccuracy = GUICtrlCreateGroup("DE Storage Accuracy", 20, 313, 375, 67)
$rdoMaybeSkip = GUICtrlCreateRadio("Possible skips", 30, 333, 120, 17)
GUICtrlSetTip(-1, "Less reliable search, but won't misidentify something else as DE storage")
GUICtrlSetState(-1, $GUI_CHECKED)
$rdoFalsePositive = GUICtrlCreateRadio("Possibly mislocated", 30, 363, 120, 17)
GUICtrlSetTip(-1, "It's going to find a damn DE storage, even if it means nuking something else on accident")
GUICtrlCreateGroup("", -99, -99, 1, 1)

GUICtrlCreateTabItem("")
